version: '2'
services:
  multichain-node:
    mem_limit: 268435456
    image: 630540209408.dkr.ecr.eu-central-1.amazonaws.com/multichain-node.develop:latest
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_PORT_RPC=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    stdin_open: true
#    secrets:
    tty: true
    external_links:
      - ip-seeder/ip-seeder:ip-seeder
    labels:
      service: multichain
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      stack_group: user
      traefik.enable: stack

    logging:
      driver: json-file
#secrets:
#  USERNAME:
#    external: true
#  PASSWORD:
#    external: true
