version: '2'
services:
  child1:
    image: child-node:auto
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: child1
    networks:
      - default

  child2:
    image: child-node:auto
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: child2
    networks:
      - default

  child3:
    image: child-node:auto
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: child3
    networks:
      - default

  child4:
    image: child-node:auto
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: child4
    networks:
      - default

  child5:
    image: child-node:auto
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: child5
    networks:
      - default

networks:
  default:
    external:
      name: multichain-network
