version: '2'
services:
  node1:
    image: multichain-node:latest
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: node1
    networks:
      - default

  node2:
    image: multichain-node:latest
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: node2
    networks:
      - default

  node3:
    image: multichain-node:latest
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: node3
    networks:
      - default

  node4:
    image: multichain-node:latest
    expose:
      - 4000
      - 4001
    tty: true
    environment:
      - BLOCKCHAIN_NAME=esmiley
      - PARENT_NODE_HOST=172.20.0.2
      - PARENT_NODE_PORT=4000
      - NODE_PORT=4000
      - NODE_RPC_PORT=4001
      - RPC_PASSWORD=asdf1234
      - RPC_USERNAME=multichainrpc
    container_name: node4
    networks:
      - default



networks:
  default:
    external:
      name: multichain-network
