version: '2'
services:
  ip-seeder:
    mem_limit: 268435456
    image: 630540209408.dkr.ecr.eu-central-1.amazonaws.com/ip-seeder.develop:latest
    environment:
      - CHECK_HOST_ALIVE_INTERVAL_MILLISECONDS=10000
    stdin_open: true
#    secrets:
    tty: true
    ports:
      - 9000:3000
    labels:
      service: multichain
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      stack_group: user
    logging:
      driver: json-file
#secrets:
#  USERNAME:
#    external: true
#  PASSWORD:
#    external: true
